const userTypes = {
  SET_USER: 'SET_USER',
  EMAIL_SIGNIN_SUCCESS: 'EMAIL_SIGNIN_SUCCESS',
  EMAIL_SIGNIN_FAIL: 'EMAIL_SIGNIN_FAIL',
  EMAIL_SIGNUP_SUCCESS: 'EMAIL_SIGNUP_SUCCESS',
  EMAIL_SIGNUP_FAIL: 'EMAIL_SIGNUP_FAIL',
  LOGOUT: 'LOGOUT',
}
export default userTypes
